import React from 'react';
import { Camera, Loader2, RefreshCw, Ban, Undo2, Coffee, Sun, Sunset, Sparkles } from 'lucide-react';

const MealLogger = ({ dailyData, plan, totalCalories, caloriesProgress, activeMeal, setActiveMeal, mealLogs, handleImageUpload, fileInputRef, analyzing, handleResetMeal, handleSkipMeal, handleUndoSkip }) => {
    return (
        <section className={`bg-gradient-to-r from-emerald-500 to-teal-600 rounded-xl shadow-lg p-5 text-white transition-opacity ${dailyData.isFinished ? 'opacity-75 pointer-events-none grayscale-[0.5]' : ''}`}>
            <div className="flex justify-between items-center mb-4">
                <div><h3 className="font-bold flex items-center gap-2"><Camera className="w-5 h-5" /> 食事記録 & AI分析</h3><div className="flex items-baseline gap-2 mt-1"><p className="text-xs text-emerald-100 opacity-90">Total: <span className="text-lg font-bold">{totalCalories}</span> / {plan.targetCalories} kcal</p><span className={`text-xs font-bold px-1.5 rounded ${totalCalories > plan.targetCalories ? 'bg-red-500' : 'bg-emerald-700'}`}>{caloriesProgress.toFixed(0)}%</span></div><div className="w-full bg-black/20 h-1.5 rounded-full mt-1 max-w-[200px]"><div className={`h-full rounded-full transition-all duration-500 ${totalCalories > plan.targetCalories ? 'bg-red-400' : 'bg-white'}`} style={{ width: `${Math.min(100, (totalCalories / plan.targetCalories) * 100)}%` }}></div></div></div>
                <span className="text-xs bg-white/20 px-2 py-1 rounded text-white font-bold">Imagen 4</span>
            </div>
            <div className="flex p-1 bg-black/20 rounded-lg mb-4">{[{ id: 'breakfast', icon: Coffee, label: '朝' }, { id: 'lunch', icon: Sun, label: '昼' }, { id: 'dinner', icon: Sunset, label: '夜' }].map((meal) => (<button key={meal.id} onClick={() => setActiveMeal(meal.id)} className={`flex-1 flex items-center justify-center gap-1 py-2 rounded-md text-sm font-bold transition-all ${activeMeal === meal.id ? 'bg-white text-teal-700 shadow-sm' : 'text-white/60 hover:bg-white/10'}`}><meal.icon className="w-3 h-3" /> {meal.label} {mealLogs[meal.id].result && <span className="ml-1 w-2 h-2 rounded-full bg-emerald-400"></span>}{mealLogs[meal.id].skipped && <span className="ml-1 w-2 h-2 rounded-full bg-slate-400"></span>}</button>))}</div>
            <div className="animate-in fade-in slide-in-from-right-2 duration-300" key={activeMeal}>
                {mealLogs[activeMeal].skipped ? (<div className="bg-black/20 rounded-lg p-6 flex flex-col items-center justify-center text-center"><Ban className="w-10 h-10 text-white/50 mb-2" /><p className="font-bold text-white">欠食 (Skipped)</p><button onClick={() => handleUndoSkip(activeMeal)} className="mt-2 bg-white/20 text-xs px-4 py-2 rounded-full flex items-center gap-1"><Undo2 className="w-3 h-3" /> 取消</button></div>) : !mealLogs[activeMeal].image ? (<div className="space-y-3"><button onClick={() => fileInputRef.current.click()} className="w-full bg-white/10 hover:bg-white/20 border-2 border-dashed border-white/30 rounded-lg p-6 flex flex-col items-center justify-center"><Camera className="w-8 h-8 mb-2 text-white/80" /><span className="text-sm font-bold">写真を撮る</span><input type="file" ref={fileInputRef} accept="image/*" className="hidden" onChange={handleImageUpload} /></button><button onClick={() => handleSkipMeal(activeMeal)} className="w-full text-white/60 text-xs py-2 flex items-center justify-center gap-1"><Ban className="w-3 h-3" /> 欠食記録</button></div>) : (<div className="space-y-4"><div className="relative rounded-lg overflow-hidden h-40 bg-black/20 flex items-center justify-center"><img src={mealLogs[activeMeal].image} alt="Food" className="h-full w-full object-cover opacity-90" />{analyzing ? <div className="absolute inset-0 bg-black/40 flex flex-col items-center justify-center"><Loader2 className="w-8 h-8 animate-spin text-white mb-2" /><span className="text-sm font-bold">AI分析中...</span></div> : <button onClick={() => handleResetMeal(activeMeal)} className="absolute top-2 right-2 bg-black/50 p-1.5 rounded-full text-white hover:bg-black/70"><RefreshCw className="w-4 h-4" /></button>}</div>{mealLogs[activeMeal].result && (<div className="bg-white text-slate-800 rounded-lg p-4 shadow-sm"><h4 className="font-bold text-lg mb-1 border-b border-slate-100 pb-2 flex justify-between">{mealLogs[activeMeal].result.name}<span className="text-emerald-600 font-extrabold">{mealLogs[activeMeal].result.calories} kcal</span></h4><div className="grid grid-cols-3 gap-2 my-3 text-center"><div className="bg-red-50 p-2 rounded"><p className="text-[10px] text-red-500 font-bold">PRO</p><p className="font-bold text-red-700">{mealLogs[activeMeal].result.protein}g</p></div><div className="bg-yellow-50 p-2 rounded"><p className="text-[10px] text-yellow-500 font-bold">FAT</p><p className="font-bold text-yellow-700">{mealLogs[activeMeal].result.fat}g</p></div><div className="bg-blue-50 p-2 rounded"><p className="text-[10px] text-blue-500 font-bold">CARB</p><p className="font-bold text-blue-700">{mealLogs[activeMeal].result.carbs}g</p></div></div><div className="bg-slate-50 p-3 rounded text-sm text-slate-600 flex gap-2 items-start"><Sparkles className="w-4 h-4 text-yellow-500 flex-shrink-0 mt-0.5" /><p className="text-xs">{mealLogs[activeMeal].result.advice}</p></div></div>)}</div>)}
            </div>
        </section>
    );
};
export default MealLogger;
